name: John Sebastian
permalink: /:title/

description: 
# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://avatars0.githubusercontent.com/u/11096727?s=400&u=90637cf356648f7adc267e53acf53365dd7064ae&v=4

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: john-seb
  linkedin: john-sebastian
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: johnmcseb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/



url: https:/john-mech-sebastian.github.io
markdown: kramdown
include: [".well-known"]


collections:
  notes:
    output: true
    permalink: /writing/:name/
  projects:
    output: true
    permalink: /projects/:name/

